apiVersion: skaffold/v2beta18
kind: Config
profiles:
  - name: dev
    build:
      local:
        push: true # true: 서버 테스트 / false: 로컬 테스트
      artifacts:
        - image: nexus.dspace.kt.co.kr/icis/icis-apigw
        # - image: feet312/simple-api # on dev server
          jib:
            args:
              - -DskipTests
              - "-Dgs ${maven_settings}"
              - "-Djib.container.environment=SPRING_PROFILES_ACTIVE=dev"
            fromImage: nexus.dspace.kt.co.kr/icis/icistr-sa-jre-runtime:v1.0.0
  - name: olv
    build:
      local:
        push: true # true: 서버 테스트 / false: 로컬 테스트
      artifacts:
        - image: nexus.dspace.kt.co.kr/icis/icis-apigw
        # - image: feet312/simple-api # on dev server 
          jib:
            args:
              - -DskipTests
              - "-Dgs ${maven_settings}"
              - "-Djib.container.environment=SPRING_PROFILES_ACTIVE=dev"
            fromImage: nexus.dspace.kt.co.kr/icis/icistr-sa-jre-runtime:v1.0.0
  - name: local
    build:
      local:
        push: true # true: 서버 테스트 / false: 로컬 테스트
        useDockerCLI: true
      artifacts: 
        - image: nexus.dspace.kt.co.kr/icis/test-apigw 
    deploy:
      kubectl:
        manifests:
          - k8s/dev/icis-apigw.yaml
          
    portForward:
     - resourceType: Service
#       resourceName: commonui-service
       resourceName: icis-apigw
       namespace: sa-app
       port: 8800
       localPort: 8800 # *Optional*