####################
### local 
####################

server:
  port: 8800
spring:
  redis:
    host: 10.217.166.60 #localhost
    port: 20876         # 6379
    username: samp
    password: samp1234
  cloud.consul.enabled: false   # disable consul on local
  
#appinfo
app-info:
  build:
    version: '@project.version@'
    timestamp: '@app.build.timestamp@'
  pod-ip: "127.0.0.1"
  pod-name: "icis-apigw-local-pod"
  node-ip: "127.0.0.1"
  node-name: "icis-apigw-local-node"
  app-name: "NBSS_ICIS"
  log-point: "EB"
    
#feign
feign:
  circuitbreaker:
    enabled: false
  client: 
    config:
      default:
        logger-level: full
        connectTimeout: 5000 # feign의 전역 timeout 설정 : 5초
        readTimeout: 5000
        loggerLevel: FULL ##basic
        
api:
  mon.url: http://icis-cmmn-bmon.sa-app.svc/
  gwadm.url: http://icis-cmmn-gwadm.sa-app.svc/
  kosgw.url: http://icis-kosgw.sa-app.svc/
#circuitbreaker
resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      slidingWindowType: COUNT_BASED
      slidingWindowSize: 10 #{통계건수}
      minimumNumberOfCalls: 10 #{최소요청횟수}
      failureRateThreshold: 60 #{실패율}
      slowCallRateThreshold: 60  #{느린요청비율}
      slowCallDurationThreshold: 3000 #{느린요청으로 간주할 시간}
      permittedNumberOfCallsInHalfOpenState: 2
      waitDurationInOpenState: 5s #{Circuit Breaker 유지시간}
      eventConsumerBufferSize: 10
  instances:
    apigw: 
      baseConfig: default
    testcircuitbreaker: 
      baseConfig: default
      
#actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
    redis:
      enabled: false
      
#routing
router.global.service.url: http://localhost:8088

#icis
icis:
  auth.flag: true           # 인증여부 
  bmon.logging.flag: true   # bmon 로깅여부 
  use.cacheapi.flag: true   # cacheapi 활성화 여부 
  circuitbreaktest.flag: false  # circuitbreak 발동여부 
  web.auth.url: http://10.217.136.198:5000/proframeWS/?ToknAvailHstVrfSO
  ui:
    remove.null:
      element: false
      string.element: false
    lgdatetime.flag: false  # true / false / choice (value = null)
    ssv.flag: false
    hash.key: 6e080839e89bf3121612c174f1fd35d~~~~~~~~~~ # key length: 256

#logging
logging:
  level:
    org.springframework.cloud.gateway: info
    reactor.netty: warn
    com.kt.icis: debug
